site_name: Ipein Info

site_url: https://anis-saied.github.io/ipein/

theme:
  name: readthedocs
  hljs_style: github #github = default
  
  #material, readthedocs
  # pip install mkdocs-cinder
  # pip install mkdocs-bootstrap
  # pip install mkdocs-windmill
  # pip install mkdocs-material
  # pip install mkdocs-readthedocs



  
#markdown_extensions:
  #- codehilite:
      #use_pygments: true  # This option enables syntax highlighting
      #pygments_style: github-dark
  #- fenced_code
  
nav:
  - Accueil: index.md
  - Chp 0 Rappel : 
    - TP1 Rappel Python : rappel/chp0_Rappel.md
  - Chp 1 Piles & files: 
    - Introduction : piles-files/introduction.md
    - Structures de Données Avancées : piles-files/cours-piles-files.md
    - TP2 Les Piles : piles-files/pile.md
    - TP3 Les Files : piles-files/file.md
  - A propos: about.md
