site_name: Ipein Info

site_url: https://anis-saied.github.io/ipein/

theme:
  name: readthedocs
  hljs_style:  github #github = default
  
  #material, readthedocs
  # pip install mkdocs-cinder
  # pip install mkdocs-bootstrap
  # pip install mkdocs-windmill
  # pip install mkdocs-material
  # pip install mkdocs-readthedocs

#<meta name="google-adsense-account" content="ca-pub-8815924748349799">
extra_css:
  - css/style.css
  
#markdown_extensions:
  #- codehilite:
      #use_pygments: true  # This option enables syntax highlighting
      #pygments_style: github-dark
  #- fenced_code
  
nav:
  - Accueil: index.md
  - Epreuves : 
    - Tests info: epreuves/tests.md
    - DS info: epreuves/ds.md
    - Examens info: epreuves/examens.md
  - Chp 0 Rappel : 
    - TP1 Rappel Python : rappel/chp0_Rappel.md
  - Chp 1 Piles & files: 
    - Introduction : piles-files/introduction.md
    - Structures de Données Avancées : piles-files/cours-piles-files.md
    - TP2 Les Piles : piles-files/pile.md
    - TP3 Les Files : piles-files/file.md
  - Chp 2 POO : 
    - Plan du cours : poo/plan.md
    - TP POO : poo/tp-poo.md
    - Introduction : poo/introduction.md
    - Classes et objets: poo/seance-1/classes-objets.md
    - Attributs: poo/seance-1/attributs.md
    - Méthodes: poo/seance-1/methodes.md
    - Constructeurs et destructeurs : poo/seance-1/constructeur-destructeur.md
    #- Exercices POO : poo/seance-1/exercices.md
    #- Exercices POO Corrigé: poo/seance-1/exercices-corrige.md
    # seance 2
    - Héritage de classes : poo/seance-2/heritage.md
    - Polymorphisme : poo/seance-2/polymorphisme.md
    # seance 3
    - Classe Object : poo/seance-3/class-object.md
    - Méthodes spéciales : poo/seance-3/methodes-speciales.md
    - Encapsulation : poo/seance-3/encapsulation.md
    # - Surcharge de méthodes : poo/seance-2/surcharge_methodes.md
    # - Utilisation avancée de la POO : poo/seance-1/poo_avancee.md
  - Chp 3 BD : 
    - Plan du cours : BD/plan.md
    - Contraintes SQL : BD/contraintes-sql.md
  - Chp 4 Simulation Numérique : 
    - Plan du cours : SimulNum/plan.md
  - Aide: 
    - Utilitaires : aide/tools.md
    - A propos : aide/about.md


  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
